sudo: false
language: node_js
node_js:
- '8'
branches:
  only:
  - develop
cache:
  directories:
  - node_modules
before_install:
- npm update
install:
- npm install
script:
- npm test -- --coverage

after_script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls